### ISSUE TITLE
Issue while updating the plugins using PlugUpdate

### ISSUE THREAD

**Issue by varun06** [codepushr/vim-go-runtime#1]
Hi,

I like this setup but I am having problem updating the plugins. When I do :PlugUpdate in vim, I get following:
<plugin name>: perl: warning: Falling back to the standard locale ("C").

And it is happening for all the plugins.

**Comment by 0x7061** [comment]
This looks like a locale warning (not an error). Try adding those into your `~/.bash_profile`:

```
# Locale
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

After that source the profile: `source ~/.bash_profile`

Hope it helps!
