### ISSUE TITLE
macVim does not use YCM

### ISSUE THREAD

**Issue by Gys** [codepushr/vim-go-runtime#3]
I had some problems with setting up YCM.

First, my build-in (?) version of vim is older then v7.4 so I got the messages:

```
YouCompleteMe unavailable: requires Vim 7.3.598+
UltiSnips requires Vim >= 7.4
```

Running 'which vim' showed an older version ('--version') of vim in /usr/bin/vim. I assume that version was found instead of the one installed with Brew ?

To solve this I modified install.sh:

```
/Applications/MacVim.app/Contents/MacOS/Vim +PlugInstall +qall
```

Running again gave another error message:

```
ycm_client_support.[so|pyd|dll] and ycm_core.[so|pyd|dll] not detected; you need to compile YCM before using it. Read the docs!
```

So using these instructions http://susu.github.io/posts/clang-completion-in-vim-with-youcompleteme/
I successfully compiled YCM 'by hand'. 

Now, my issue: MacVim still does not use YCM. Running your install.sh again does not help either. The command ' /Applications/MacVim.app/Contents/MacOS/Vim +PlugInstall +qall' keeps coming with 'ycm_client_....' error although a compiled version is now in '~/.vim/bundle/YouCompleteMe/third_party/ycmd'. So how do I setup vim-go-runtime and MacVim to use YCM ?

**Comment by Gys** [comment]
I solved it. First I deleted the complete .vim-go-runtime dir and downloaded it again. Then I edited the install.sh script as before. Finally I ran the install.sh script and this time everything went well.

**Comment by 0x7061** [comment]
The thing is, I am already using a 7.4+ version via homebrew, therefore I didn't get the warnings. It makes sense that you run:

```
/Applications/MacVim.app/Contents/MacOS/Vim +PlugInstall +qall
```

with a high enough Vim version, so good job :)

The problem with:

```
ycm_client_support.[so|pyd|dll] and ycm_core.[so|pyd|dll] not detected;
```

is natural, because usually you need to compile YouCompleteMe and in my configuration I'm using vim-plug and therefore it is set up to compile after installing the plugin. It should work even with the error.

See #2

**Comment by 0x7061** [comment]
I just updated the README that one needs to install a high enough version of Vim.
Closing this for now.
