### ISSUE TITLE
cmake and python-dev

### ISSUE THREAD

**Issue by Gys** [codepushr/vim-go-runtime#4]
I installed this on a Ubuntu machine and it failed because cmake and python-dev where not installed. It was not obvious from the output because it says something along 'could not compile see readme'. But I remembered this was needed for YCM. After installing everything went well.

**Comment by 0x7061** [comment]
Thanks for pointing that out :) I will add it to the README!

**Comment by 0x7061** [comment]
@Gys Do you know what the python-dev equivalent is on Mac OS? I think it's already included in the Xcode command line tools but if someone doesn't want to install Xcode what should he do?

For cmake there's a brew formula:

```
brew install cmake
```

But for python-dev?

**Comment by Gys** [comment]
I also think cmake and python-dev are installed as part of xcode (which is
installed already on my mac). There where no complaints on these while I
installed vim-go-runtime.

Googling for python-dev I only find references to xcode in case python-dev
headers are needed. From what I understand its part of a 'real' python
install.
For example:
http://docs.python-guide.org/en/latest/starting/install/osx/

**Comment by 0x7061** [comment]
Closing this for now.
