### ISSUE TITLE
Not an editor command :GoInstallBinaries

### ISSUE THREAD

**Issue by Gr1N** [codepushr/vim-go-runtime#5]
Hi!

I got strange error "Not an editor command :GoInstallBinaries", while trying to install go binaries inside vim. Maybe you know in what is problem?

Thnx!

**Comment by Gr1N** [comment]
Sorry, I found what the problem was.

**Comment by 0x7061** [comment]
Glad you found it! Could you still post a short line what the problem was and how you solved it? Just in case someone else stumbles over this issue. Thanks!
