### ISSUE TITLE
unknown function plug#begin

### ISSUE THREAD

**Issue by Gys** [codepushr/vim-go-runtime#6]
I installed vim-go-runtime on Ubuntu 14.04.3
Everything seemed to install just fine, although I had to use 'sudo sh install.sh'.

But if I now use 'vim' I get errors related to 'unknown function plug#begin' while 'sudo vim' works fine. So I need always to use 'sudo' = be root. Not optimal.

Worse, I have another problem that seems related: inside vim I get the error 'vim.go: $GOPATH is not set'. Even though outside vim it is set for the current user - but that probably works not for root.

Any idea how to solve this for the current user ?

**Comment by hansrodtang** [comment]
Why did you have to use `sudo` to run the installer? The error here is that you have installed the scripts in the root user's home folder, not your own home folder.

**Comment by Gys** [comment]
There is only one user which is the root user. So all is installed in ~/home/gys/.vim*

And I choose to use 'sudo' because only using 'sh install.sh' resulted in:

```
You don't have permission to create /home/gys/.vim/autoload.
Setting up base config ...
install.sh: 11: install.sh: cannot create /home/gys/.vimrc: Permission denied
<and more of those>
```

**Comment by 0x7061** [comment]
Were you able to solve this? Sadly I never used it on a system with only a root user :/

**Comment by Gys** [comment]
Sorry, did not find the time yet to take a deeper look.

**Comment by 0x7061** [comment]
Never ran this as root before and I'm not sure if this is suppose to work this way. Closing this for now!
